//
//  Workspace.swift
//  Config
//
//  Created by 조용인 on 3/8/25.
//

import ProjectDescription

let workspace = Workspace(
  name: "PIDA",
  projects: [
    "./Projects/**"
  ],
  schemes: [
    .scheme(
      name: "Debug-PIDA",
      buildAction: .buildAction(targets: [.project(path: "./Projects/PIDA", target: "PIDA_DEV")]),
      runAction: .runAction(configuration: .debug),
      archiveAction: .archiveAction(configuration: .debug),
      profileAction: .profileAction(configuration: .debug),
      analyzeAction: .analyzeAction(configuration: .debug)
    ),
    .scheme(
      name: "PROD-PIDA",
      buildAction: .buildAction(targets: [.project(path: "./Projects/PIDA", target: "PIDA")]),
      runAction: .runAction(configuration: .release),
      archiveAction: .archiveAction(configuration: .release),
      profileAction: .profileAction(configuration: .release),
      analyzeAction: .analyzeAction(configuration: .release)
    )
  ],
  generationOptions: .options(autogeneratedWorkspaceSchemes: .disabled)
)
